spring:
  cache:
    type: redis
    redis:
      cache-null-values: false
      time-to-live: 3600000ms
  redis:
    host: 127.0.0.1
    port: 6379
    database: 5
    password: tyzfpt_test@211
logging:
  level:
    root: info